name: py311-whislive-client
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pip>=24.0
  - pip:
    # client
    - pyaudio
    - numpy
    - websocket-client
    # dev
    - ruff>=0.0.271
    - yapf>=0.33.0
    - isort>=5.12.0
    - pytest>=7.3.1
    - ipython
    - pyright
